version: '3'
services:
  piwigo:
    container_name: piwigo
    image: brief-piwigo
    networks:
      - piwigo
    ports:
      - "80:80"

  mysql:
    container_name: piwigo_mysql #nom à utiliser lors de la connexion de la DB a piwigo "Database configuration : Host = <Nom_du_conteneur>"
    image: mysql:8.0.18
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - piwigo
    environment: #TODo : Passer les secrets en variables d'environnement, format : "${ma_variable_denvironnement}"
      MYSQL_USER: "piwigo" #TODO
      MYSQL_PASSWORD: "piwigo" #TODO
      MYSQL_DATABASE: "piwigo" #TODO
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

# TODO : Passer proxy Nginx
# nginx:
#   image:
#     container_name: 
#     volumes: 

#     networks: 
#       - piwigo

#     links: 
#       - piwigo
#     ports:
#       - 80:80




networks:
  piwigo: