version: '3'
services:
  piwigo:
    container_name: piwigo
    image: brief-piwigo
    networks:
      - piwigo
    ports:
      - "80:80"

  mysql:
    container_name: piwigo_mysql
    image: mysql:8.0.18
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - piwigo
    environment: #TODo : Passer les secrets en variables d'environnement, format : "${ma_variable_denvironnement}"
      MYSQL_USER: "piwigo" #TODO
      MYSQL_PASSWORD: "piwigo" #TODO
      MYSQL_DATABASE: "piwigo" #TODO
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

networks:
  piwigo: